# Generated by Django 4.0.1 on 2022-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0003_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.TextField(null=True),
        ),
    ]
