# Generated by Django 4.0.1 on 2022-11-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0004_product_nutrition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nutrition',
            new_name='nutritionalvalue',
        ),
    ]
