# Generated by Django 4.0.1 on 2022-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0007_rename_datetime_ordered_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutritionalvalue',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
