# Generated by Django 4.0.1 on 2022-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0009_product_image_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='macros',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_value',
            field=models.TextField(null=True),
        ),
    ]
