# Generated by Django 4.0.1 on 2022-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0010_product_allergens_product_macros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
