# Generated by Django 4.0.1 on 2022-12-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0011_alter_basketitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nutritional_value',
            new_name='nutritional_information',
        ),
    ]
