# Generated by Django 4.0.1 on 2023-01-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0014_order_country_order_name_order_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postcode',
        ),
    ]
