# Generated by Django 4.0.1 on 2023-01-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0016_order_country_order_name_order_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
