# Generated by Django 4.0.1 on 2023-01-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0017_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sname',
            field=models.TextField(default=''),
        ),
    ]
