# Generated by Django 4.0.1 on 2023-02-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0018_order_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.TextField(null=True),
        ),
    ]
