# Generated by Django 4.0.1 on 2023-02-21 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2gshop', '0020_recommendations_weighttracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttracking',
            name='date_logged',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 16, 50, 50, 263064)),
        ),
    ]
